spring:
  application:
    name: backend
  profiles:
    active: dev # 기본적으로 dev 프로파일 활성화

  # Common Jackson Configuration (공통)
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  
  # Common JPA Configuration (공통)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

